name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - prod
      - shared

jobs:
  terraform:
    if: ${{ !startsWith(github.event.head_commit.message, 'ci(dispatch):') && !contains(github.event.head_commit.message, '[ci-skip]') }}
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      TF_VAR_project: potent-result-454023-m7
      TF_VAR_region: asia-northeast3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set working directory based on branch
        id: set-dir
        run: |
          if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "dir=terraform/envs/dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "prod" ]]; then
            echo "dir=terraform/envs/prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "shared" ]]; then
            echo "dir=terraform/envs/shared" >> $GITHUB_OUTPUT
          else
            echo "❌ Unknown branch: ${GITHUB_REF##*/}"
            exit 1
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ steps.set-dir.outputs.dir }}

      - name: Terraform Plan
        id: tfplan
        run: |
          terraform plan -detailed-exitcode || echo "exit=$?" >> $GITHUB_OUTPUT
        working-directory: ${{ steps.set-dir.outputs.dir }}

      - name: Terraform Apply
        if: steps.tfplan.outcome == 'success' && steps.tfplan.outputs.exit == '2'
        run: terraform apply -auto-approve
        working-directory: ${{ steps.set-dir.outputs.dir }}